### ISSUE TITLE
Join forces

### ISSUE THREAD

**Issue by sagikazarmark** [umpirsky/Gravatar#1]
Hey there

Not sure how actively you maintain this package and what effort you invest in it, but do you want to join forces:

http://gravatarphp.com/

**Comment by umpirsky** [comment]
Hi @sagikazarmark! :)

Well, I just built it for fun. Not sure if anyone uses it to be honest. :)

Looks like what I've done is a part of what you already have in gravatarphp. What do you suggest?

**Comment by sagikazarmark** [comment]
I usually suggest merging codebase and teams in these cases. If you read the website you know why I started building this stuff. I am pretty sure that you experienced those things as well. Your library seems to be kind of an exception (documented, well-tested).

So if you are willing to join forces, let's compare features, implement the missing ones in gravatarphp and deprecate this in favour of that. I would also add you to the organization, since you are also an author.

WDYT?

**Comment by umpirsky** [comment]
@sagikazarmark What I think is that there is no feature in this library that you don't have already, that's why I see no need for merging. :)

Or am I missing something?

**Comment by sagikazarmark** [comment]
Haven't done any comparison closely, so you might be right :wink:

**Comment by umpirsky** [comment]
I am not against, I just don't think it's worth it. :)

**Comment by sagikazarmark** [comment]
I accept that as well. Well, If you ever change my mind, you know how to find me.

**Comment by umpirsky** [comment]
@sagikazarmark :+1:
